version: '3'

services:
  sqlledger:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    healthcheck:
      test: ["/opt/mssql-tools/bin/sqlcmd", "-H", "http://0.0.0.0:1433", "-U", "sa", "-P", "Bosch@123", "-d", "autotracelite", "-Q", "SELECT * FROM sys.objects"]
      interval: 15s
      timeout: 200s
      retries: 5
    environment:
      SA_PASSWORD: "Bosch@123"
      ACCEPT_EULA: "Y"
    volumes:
      - mysql-data:/var/lib/mssql/data

volumes:
  mysql-data:
